### ISSUE TITLE
Build is fail

### ISSUE THREAD

**Issue by bborysenko** [aubm/hugo-code-editor-theme#10]
It seems issue with https://github.com/aubm/hugo-code-editor-theme/blob/master/static/css/theme.scss#L50:

```
$ npm run build
...
[17:52:53] { Error: static/css/_mixins.scss
Error: You may not @extend an outer selector from within @media.
       You may only @extend selectors within the same directive.
       From "@extend .no-padding-left-and-right" on line 50 of static/css/theme.scss
        on line 1 of static/css/_mixins.scss
>> .no-padding-left-and-right {
   ^

    at options.error (/Users/bborysenko/src/hugo-code-editor-theme/node_modules/node-sass/lib/index.js:286:26)
  status: 1,
  file: '/Users/bborysenko/src/hugo-code-editor-theme/static/css/_mixins.scss',
  line: 1,
  column: 1,
  message: 'static/css/_mixins.scss\nError: You may not @extend an outer selector from within @media.\n       You may only @extend selectors within the same directive.\n       From "@extend .no-padding-left-and-right" on line 50 of static/css/theme.scss\n        on line 1 of static/css/_mixins.scss\n>> .no-padding-left-and-right {\n   ^\n',
  formatted: 'Error: You may not @extend an outer selector from within @media.\n       You may only @extend selectors within the same directive.\n       From "@extend .no-padding-left-and-right" on line 50 of static/css/theme.scss\n        on line 1 of static/css/_mixins.scss\n>> .no-padding-left-and-right {\n   ^\n',
  messageFormatted: '\u001b[4mstatic/css/_mixins.scss\u001b[24m\nError: You may not @extend an outer selector from within @media.\n       You may only @extend selectors within the same directive.\n       From "@extend .no-padding-left-and-right" on line 50 of static/css/theme.scss\n        on line 1 of static/css/_mixins.scss\n>> .no-padding-left-and-right {\n   ^\n',
  messageOriginal: 'You may not @extend an outer selector from within @media.\nYou may only @extend selectors within the same directive.\nFrom "@extend .no-padding-left-and-right" on line 50 of static/css/theme.scss\n',
  relativePath: 'static/css/_mixins.scss',
  name: 'Error',
  stack: 'Error: static/css/_mixins.scss\nError: You may not @extend an outer selector from within @media.\n       You may only @extend selectors within the same directive.\n       From "@extend .no-padding-left-and-right" on line 50 of static/css/theme.scss\n        on line 1 of static/css/_mixins.scss\n>> .no-padding-left-and-right {\n   ^\n\n    at options.error (/Users/bborysenko/src/hugo-code-editor-theme/node_modules/node-sass/lib/index.js:286:26)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-sass' }
[17:52:53] Finished 'css' after 94 ms
```

**Comment by zodman** [comment]
+1

**Comment by dnkls** [comment]
+1

**Comment by a-dubaj** [comment]
+1

**Comment by AidanNelson** [comment]
Just ran into this myself.  For anyone else who comes along to this issue, it can be fixed by replacing the ~~two~~ one  `@extend .no-padding-left-and-right;` statements within the @media query from the theme.scss file with the following:

```
    padding-left: 0px;
    padding-right: 0px;
```
The result should be an identical css output file, as far as I know.

**Comment by zodman** [comment]
@AidanNelson  make a PR

**Comment by AidanNelson** [comment]
@zodman Done.
